baseURL: "https://0xzer0x.github.io"
languageCode: "en-us"
title: "Youssef Fathy"
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

module:
  imports:
    - path: github.com/hugomods/icons/vendors/simple-icons
    - path: github.com/hugomods/icons/vendors/font-awesome
    - path: github.com/hugomods/icons/vendors/mdi

minify:
  disableXML: true

outputs:
  home:
    - HTML
    - RSS
    - JSON
