languageName: AR
languagedirection: rtl
title: يوسف فتحي
weight: 2
taxonomies:
  project: projects
  category: categories
  tag: tags
  series: series
menu:
  main:
    - identifier: projects
      name: مشاريع
      url: projects/
      weight: 1
    - identifier: blog
      name: مدونة
      url: blog/
      weight: 2
    - identifier: resume
      name: سيرة ذاتية
      url: resume/
      weight: 3
    - name: وسوم
      url: tags/
      weight: 4
    - name: بحث
      url: search/
      weight: 5

params:
  profileMode:
    title: يوسف فتحي
    subtitle: مهندس DevOps

  editPost:
    Text: اقترح تعديل
    URL: https://github.com/0xzer0x/0xzer0x.github.io/tree/main/content
    appendFilePath: true
