[settings]
all_compile = false
lockfile = true

[tools]
# NOTE: Hugo
go = "1.23"
hugo = "0.160.1"
# NOTE: Linters and formatters
oxfmt = "0.44.0"
tombi = "0.9.17"
# NOTE: Utils
prek = "0.3"

[tasks.install]
description = "Install all dependencies"
alias = "i"
run = ["mise --locked install", "hugo mod vendor", "prek install"]
